// define the properties file
ext.configFile = file "gradle.properties"
configFile.withReader {
    // read config.  it shall from now on be referenced as simply config or as project.config
    def prop = new Properties()
    prop.load(it)
    project.ext.config = new ConfigSlurper().parse prop
}

// For those who want the bleeding edge
buildscript {
    repositories {
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net"
        }
        maven {
            name = "sponge"
            url = "https://repo.spongepowered.org/maven"
        }
    }
    dependencies {
        classpath 'com.anatawa12.forge:ForgeGradle:2.3-1.0.8'
        classpath 'org.spongepowered:mixingradle:0.6-SNAPSHOT'
    }
}
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'maven'
apply plugin: 'org.spongepowered.mixin'

///////////////////////////////////////////////////
// IDE Settings
///////////////////////////////////////////////////
idea {
    project {
        languageLevel = '1.8'
    }
}
def getGitHash() {
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    } catch (Exception e) {
        return "unknown"
    }
}

///////////////////////////////////////////////////
// ForgeGradle
///////////////////////////////////////////////////
def gitHash = getGitHash()
version = "${config.mod_version}-${gitHash}"
group = project.hasProperty('group') ? project.getProperties().get('group') : config.group_name
archivesBaseName = "${config.mod_id}-${config.minecraft_version}"
sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

minecraft {
    version = config.minecraft_version + "-" + config.forge_version // grab latest forge
    runDir = "run"

    mappings = config.mcp_mappings
    makeObfSourceJar = false // an Srg named sources jar is made by default. uncomment this to disable.

    replace '@mod_version@', version
    replace '@mod_id@', config.mod_id
    replace '@ci_build@', hasProperty("CIRevision") ? 'true' : 'false'

    replaceIn 'TwilightForestMod.java'
    replace '@VERSION@', project.version
}

processResources {
    //replaceIn 'assets/twilightforest/patchouli_books/guide/book.json'
    //replace '@EDITION@', project.version

    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include '**/*.info'
        //include '**/*.properties'
        include 'assets/twilightforest/patchouli_books/guide/book.json'

        // replace version and mcversion
        expand(['version'          : project.version,
                'mcversion'        : project.minecraft.version,
                'forge_version'    : config.forge_version,
                'mod_version'      : config.mod_version,
                'minecraft_version': config.minecraft_version,
                'edition'          : (project.version - (config.mod_version + '.')),
                's'                : '$'])
    }

    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
        exclude 'assets/twilightforest/patchouli_books/guide/book.json'
    }
}

compileJava {
    options.encoding = 'UTF-8'
}

jar {
    classifier = 'universal'
    manifest {
        attributes 'FMLAT': 'tf_at.cfg'
    }
}

repositories {
    maven {
        name 'K4Unl\'s Maven' // JEI + Mantle + TCon
        url 'https://modmaven.dev'
    }
    maven {
        name 'tterrag\'s Maven' // CTM
        url 'https://maven.tterrag.com'
    }
    maven {
        name 'Jared\'s Maven' // Immersive Engineering + Patchouli
        url 'https://blamejared.com/maven'
    }
    maven {
        name 'Curseforge Maven' // Baubles + Thaumcraft
        url 'https://minecraft.curseforge.com/api/maven'
    }
    maven {
        name 'Curse Maven' // Mowzie's Mobs
        url 'https://www.cursemaven.com'
    }
    maven {
        name 'CleanroomMC' // Cleanroom MC
        url 'https://maven.cleanroommc.com'
    }
    maven {
        name 'Sponge' // MixinGradle
        url 'https://repo.spongepowered.org/maven'
    }
}

dependencies {
    // progwml6
    deobfCompile "mezz.jei:jei_${minecraft_version}:${jei_version}"

    deobfCompile "slimeknights.mantle:Mantle:${minecraft_sub_version}-${mantle_version}"
    deobfCompile "slimeknights:TConstruct:${minecraft_version}-${tcon_version}"

    // tterrag
    deobfCompile "team.chisel.ctm:CTM:MC${minecraft_version}-${ctm_version}"
    //deobfCompile "team.chisel:Chisel:MC${minecraft_version}-${chisel_version}"

    // blamejared
    deobfCompile "blusunrize:ImmersiveEngineering:${immersive_engineering_version}"
    deobfCompile "vazkii.patchouli:Patchouli:${patchouli_version}"

    // player
    deobfCompile "net.sengir.forestry:forestry_${minecraft_version}:${forestry_version}"

    // curseforge
    deobfCompile "baubles:Baubles:${minecraft_sub_version}:${baubles_version}"
    deobfCompile "thaumcraft:Thaumcraft:${minecraft_version}:${thaumcraft_version}"

    // LLibrary must be 1.7.9 or it'll crash during testing
    compileOnly "curse.maven:llibrary-243298:2504999"
    deobfCompile "curse.maven:mowzies-mobs-250498:3048685"

    deobfCompile "curse.maven:constructs-armory-287683:3174535"

    // MixinBooter
    annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
    annotationProcessor 'com.google.guava:guava:32.1.2-jre'
    annotationProcessor 'com.google.code.gson:gson:2.8.9'

    implementation('zone.rong:mixinbooter:10.5') {
        transitive = false
    }
    annotationProcessor('zone.rong:mixinbooter:10.5') {
        transitive = false
    }
}

mixin {
    add sourceSets.main, "twilightforest.mixins.refmap.json"
}

task createPom {
    doLast {
        pom {
            project {
                groupId project.group
                artifactId project.archivesBaseName
                version project.version

                inceptionYear '2012'
                licenses {
                    license {
                        name 'LGPL 2.1'
                        url 'https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html'
                        distribution 'repo'
                    }
                }
            }
        }.writeTo(libsDir.path + "/" + project.archivesBaseName + "-" + project.version + ".pom")
    }
}

build.dependsOn createPom
